server:
  port: 8081

spring:
  profiles:
    active: "${ACTIVE_PROFILE:dev}"
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:${DB_NAME:prod};MODE=PostgreSQL"
    username: "${DB_USERNAME:prod}"
    password: "${DB_PASSWORD:SuperSecret}"
    hikari:
      connection-timeout: "${CONNECTION_TIMEOUT:5000}"
      maximum-pool-size: "${MAX_POOL_SIZE:20}"
      pool-name: "${POOL_NAME:app-hikari-pool-name}"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: never
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

bank:
  internalTransferLimit: 100000.00
  externalTransferLimit: 15000.00