spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:${DB_NAME:test};MODE=PostgreSQL"
    username: "${DB_USERNAME:test}"
    password: "${DB_PASSWORD:test}"
    hikari:
      connection-timeout: "${CONNECTION_TIMEOUT:5000}"
      maximum-pool-size: "${MAX_POOL_SIZE:20}"
      pool-name: "${POOL_NAME:test-hikari-pool-name}"

bank:
  internalTransferLimit: 100000.00
  externalTransferLimit: 15000.00